"""
runtime/tools/tool_planner.py
Phase 6.5 Hypothesis-Driven Tool Selection and Action Planning.

Enforces:
- Matching active hypotheses and research gaps to registered tool capabilities.
- Trust level verification before action planning.
- Target scope validation through AuthorizedTargetAdapter.
- Argument validation and injection defense through ToolArgumentValidator.
- Pre-execution budget reservation through ToolBudgetTracker.
- Production of authorized ToolActionContracts or explicit safe rejection decisions.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

from runtime.tools.action_contract import ToolActionContract
from runtime.tools.argument_validator import ToolArgumentValidator
from runtime.tools.budget_tracker import ToolBudgetTracker
from runtime.tools.models import ToolActionStatus, ToolCapabilityCategory, ToolRegistration
from runtime.tools.registry import ToolRegistry
from runtime.tools.target_adapter import AuthorizedTargetAdapter


@dataclass
class ToolSelectionDecision:
    """Decision generated by the tool planner."""
    is_selected: bool
    action: ToolActionContract | None = None
    tool: ToolRegistration | None = None
    rejection_reason: str = ""
    rationale: str = ""

    def to_dict(self) -> dict[str, Any]:
        return {
            "is_selected": self.is_selected,
            "action": self.action.to_dict() if self.action else None,
            "tool_id": self.tool.tool_id if self.tool else None,
            "rejection_reason": self.rejection_reason,
            "rationale": self.rationale,
        }


class ToolPlanner:
    """
    Hypothesis-driven tool planner and action authorizer.
    """

    # Map vulnerability class to capability and tool ID preferences
    VULN_CAPABILITY_MAP: dict[str, tuple[ToolCapabilityCategory, str]] = {
        "IDOR_BOLA": (ToolCapabilityCategory.HTTP_ANALYSIS, "synthetic_http_probe"),
        "SECURITY_MISCONFIGURATION": (ToolCapabilityCategory.HEADER_CHECK, "synthetic_header_check"),
        "AUTH_BYPASS": (ToolCapabilityCategory.AUTH_VERIFICATION, "synthetic_auth_comparator"),
        "INFORMATION_DISCLOSURE": (ToolCapabilityCategory.HTTP_ANALYSIS, "synthetic_http_probe"),
    }

    def __init__(
        self,
        mission_id: str,
        registry: ToolRegistry,
        target_adapter: AuthorizedTargetAdapter,
        argument_validator: ToolArgumentValidator,
        budget_tracker: ToolBudgetTracker,
    ) -> None:
        self.mission_id = mission_id
        self.registry = registry
        self.target_adapter = target_adapter
        self.argument_validator = argument_validator
        self.budget_tracker = budget_tracker

    def plan_tool_action(
        self,
        hypothesis: Any,  # HypothesisRecord or similar
        iteration_id: int,
        base_url: str = "http://127.0.0.1:8080",
        preferred_tool_id: str | None = None,
        custom_args: dict[str, Any] | list[str] | None = None,
    ) -> ToolSelectionDecision:
        """
        Plan and authorize a tool action for a given hypothesis.
        """
        vuln_class = getattr(hypothesis, "vulnerability_class", "INFORMATION_DISCLOSURE")
        hyp_id = getattr(hypothesis, "hypothesis_id", "HYP-UNKNOWN")
        target_asset = getattr(hypothesis, "target_asset", "") or base_url

        # 1. Target URL resolution
        if not target_asset.startswith("http://") and not target_asset.startswith("https://"):
            full_target = f"{base_url.rstrip('/')}/{target_asset.lstrip('/')}"
        else:
            full_target = target_asset

        # 2. Target validation through AuthorizedTargetAdapter
        target_result = self.target_adapter.validate_target(full_target)
        if not target_result.is_authorized:
            return ToolSelectionDecision(
                is_selected=False,
                rejection_reason=f"TARGET_VALIDATION_FAILED: {target_result.rejection_reason}",
                rationale=f"Target '{full_target}' is not authorized for mission '{self.mission_id}'",
            )

        # 3. Tool Selection
        if preferred_tool_id:
            tool = self.registry.get_tool(preferred_tool_id)
            if not tool:
                return ToolSelectionDecision(
                    is_selected=False,
                    rejection_reason=f"TOOL_NOT_REGISTERED: {preferred_tool_id}",
                    rationale=f"Requested preferred tool '{preferred_tool_id}' does not exist",
                )
        else:
            _, default_tool_id = self.VULN_CAPABILITY_MAP.get(
                vuln_class, (ToolCapabilityCategory.HTTP_ANALYSIS, "synthetic_http_probe")
            )
            tool = self.registry.get_tool(default_tool_id)
            if not tool:
                # Fallback to any available tool
                available_tools = self.registry.list_tools()
                if not available_tools:
                    return ToolSelectionDecision(
                        is_selected=False,
                        rejection_reason="NO_AVAILABLE_TOOLS",
                        rationale="Registry contains no available tools",
                    )
                tool = available_tools[0]

        # 4. Tool authorization validation
        try:
            validated_tool = self.registry.validate_tool_for_execution(tool.tool_id)
        except Exception as exc:
            return ToolSelectionDecision(
                is_selected=False,
                rejection_reason=f"TOOL_AUTHORIZATION_FAILED: {exc}",
                rationale=f"Tool '{tool.tool_id}' is not authorized for execution",
            )

        # 5. Argument preparation & schema validation
        if custom_args is not None:
            raw_args = custom_args
        else:
            if tool.execution_adapter == "orchestrator_adapter":
                raw_args = ["-s", "-i", target_result.normalized_target]
            else:
                raw_args = {"target": target_result.normalized_target, "timeout": min(10.0, validated_tool.timeout_limit)}

        arg_result = self.argument_validator.validate_arguments(
            tool=validated_tool,
            raw_args=raw_args,
            authorized_target=target_result.normalized_target,
        )
        if not arg_result.is_valid:
            return ToolSelectionDecision(
                is_selected=False,
                tool=validated_tool,
                rejection_reason=f"ARGUMENT_VALIDATION_FAILED: {arg_result.rejection_reason}",
                rationale=f"Arguments rejected by schema security validator for tool '{validated_tool.tool_id}'",
            )

        # 6. Action Contract creation
        action_id = f"ACT-{hyp_id[:8]}-{validated_tool.tool_id[:8]}-iter{iteration_id}"
        action = ToolActionContract(
            action_id=action_id,
            mission_id=self.mission_id,
            iteration_id=iteration_id,
            hypothesis_id=hyp_id,
            tool_id=validated_tool.tool_id,
            target_id=hyp_id,
            normalized_target=target_result.normalized_target,
            action_type="SECURITY_PROBE",
            validated_arguments=arg_result.validated_arguments,
            scope_fingerprint=target_result.scope_fingerprint,
            timeout=validated_tool.timeout_limit,
            provenance={"mission_id": self.mission_id, "planner": "ToolPlanner"},
        )

        # Compute and attach authorization digest
        action.authorization_digest = action.calculate_authorization_digest()

        # 7. Budget verification & reservation
        action_fingerprint = f"{validated_tool.tool_id}:{target_result.normalized_target}"
        budget_ok, budget_reason = self.budget_tracker.check_and_reserve(
            action_id=action.action_id,
            iteration_id=iteration_id,
            action_fingerprint=action_fingerprint,
            estimated_duration=5.0,
            estimated_bytes=4096,
        )
        if not budget_ok:
            action.transition_to(ToolActionStatus.REJECTED, reason=budget_reason)
            return ToolSelectionDecision(
                is_selected=False,
                action=action,
                tool=validated_tool,
                rejection_reason=budget_reason,
                rationale=f"Budget check failed for action '{action.action_id}'",
            )

        # Transition action from CREATED -> VALIDATING -> AUTHORIZED
        action.transition_to(ToolActionStatus.VALIDATING, reason="SCHEMA_AND_SCOPE_VALIDATED")
        action.transition_to(ToolActionStatus.AUTHORIZED, reason="BUDGET_AND_POLICY_APPROVED")

        rationale = (
            f"Selected '{validated_tool.tool_name}' ({validated_tool.tool_id}) to test hypothesis "
            f"'{hyp_id}' ({vuln_class}) against target '{target_result.normalized_target}'."
        )

        return ToolSelectionDecision(
            is_selected=True,
            action=action,
            tool=validated_tool,
            rejection_reason="",
            rationale=rationale,
        )
